"""add platform admin

Revision ID: fa3aaa5f04a0
Revises: 1e343dae5fc4
Create Date: 2026-05-09 21:50:01.574272+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fa3aaa5f04a0"
down_revision: str | None = "1e343dae5fc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_admin",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_via", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "created_via IN ('bootstrap_cli', 'admin_cli')",
            name=op.f("ck_platform_admin_created_via_allowed"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_admin")),
        sa.UniqueConstraint("username", name=op.f("uq_platform_admin_username")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("platform_admin")
    # ### end Alembic commands ###
