"""add health marker

Revision ID: 660e1a12a41a
Revises: 0bf0aa5ccee1
Create Date: 2026-05-09 16:48:10.240655+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "660e1a12a41a"
down_revision: str | None = "0bf0aa5ccee1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_marker",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_marker")),
        sa.UniqueConstraint("label", name=op.f("uq_health_marker_label")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("health_marker")
    # ### end Alembic commands ###
