"""add tenant dispatcher carer operation participation auditlog

Revision ID: c1465f544fd0
Revises: fa3aaa5f04a0
Create Date: 2026-05-10 14:11:42.304671+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c1465f544fd0"
down_revision: str | None = "fa3aaa5f04a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("city_label", sa.String(length=120), nullable=False),
        sa.Column("url_token", sa.String(length=64), nullable=False),
        sa.Column("access_code_hash", sa.String(length=255), nullable=True),
        sa.Column("access_code_active", sa.Boolean(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('planned', 'active', 'closed')", name=op.f("ck_operation_status_allowed")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation")),
        sa.UniqueConstraint("url_token", name=op.f("uq_operation_url_token")),
    )
    op.create_table(
        "tenant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('applied', 'active', 'deactivated')", name=op.f("ck_tenant_status_allowed")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
        sa.UniqueConstraint("name", name=op.f("uq_tenant_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenant_slug")),
    )
    op.create_table(
        "carer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_carer_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carer")),
        sa.UniqueConstraint("tenant_id", "username", name="uq_carer_tenant_id_username"),
    )
    op.create_table(
        "dispatcher",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_dispatcher_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispatcher")),
        sa.UniqueConstraint("tenant_id", "username", name="uq_dispatcher_tenant_id_username"),
    )
    op.create_table(
        "operation_tenant_participation",
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('owner', 'participant')",
            name=op.f("ck_operation_tenant_participation_role_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operation.id"],
            name=op.f("fk_operation_tenant_participation_operation_id_operation"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_operation_tenant_participation_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "operation_id", "tenant_id", name=op.f("pk_operation_tenant_participation")
        ),
    )
    op.create_index(
        "ix_operation_tenant_participation_owner_unique",
        "operation_tenant_participation",
        ["operation_id"],
        unique=True,
        postgresql_where=sa.text("role = 'owner'"),
    )
    op.create_table(
        "operation_audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("actor_dispatcher_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_kind", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_dispatcher_id"],
            ["dispatcher.id"],
            name=op.f("fk_operation_audit_log_actor_dispatcher_id_dispatcher"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operation.id"],
            name=op.f("fk_operation_audit_log_operation_id_operation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_audit_log")),
    )
    op.create_index(
        "ix_operation_audit_log_operation_id_at",
        "operation_audit_log",
        ["operation_id", "at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_operation_audit_log_operation_id_at", table_name="operation_audit_log")
    op.drop_table("operation_audit_log")
    op.drop_index(
        "ix_operation_tenant_participation_owner_unique",
        table_name="operation_tenant_participation",
        postgresql_where=sa.text("role = 'owner'"),
    )
    op.drop_table("operation_tenant_participation")
    op.drop_table("dispatcher")
    op.drop_table("carer")
    op.drop_table("tenant")
    op.drop_table("operation")
    # ### end Alembic commands ###
